#!/usr/bin/env python3
# Generated by generate_stages.py, do not edit by hand
# Run 'make pr-build-script' to regenerate this file
"""Pull-request build check (no push).

Build every CHANGED image and all its DOWNSTREAM dependents, in dependency
order, in a single job. Each image is built into the local docker image store
and tagged with its registry references, so a dependent's FROM / COPY --from
resolves against the just-built local image. Unchanged upstream dependencies
are pulled from the registry (published on main). Nothing is pushed.
"""
import datetime
import os
import subprocess

REGISTRY = "ghcr.io"
REPO_NAME = os.environ.get("REPO_NAME", "cynkra/docker-images")

# image -> {"path", "archs", "deps"}  (generated)
IMAGES = {
    'alma9': {"path": 'alma9', "archs": ['amd64', 'arm64'], "deps": []},
    'alma9-rig': {"path": 'alma9/rig', "archs": ['amd64', 'arm64'], "deps": ['alma9']},
    'alma9-rig-rrel': {"path": 'alma9/rig/rrel', "archs": ['amd64', 'arm64'], "deps": ['alma9-rig']},
    'alma9-rig-rrel-coinor': {"path": 'alma9/rig/rrel/coinor', "archs": ['amd64', 'arm64'], "deps": ['alma9-rig-rrel']},
    'clang18-duckdb': {"path": 'clang18-duckdb', "archs": ['amd64'], "deps": []},
    'forky': {"path": 'forky', "archs": ['amd64', 'arm64'], "deps": []},
    'forky-gcc': {"path": 'forky/gcc', "archs": ['amd64', 'arm64'], "deps": ['forky']},
    'forky-gcc-rig': {"path": 'forky/gcc/rig', "archs": ['amd64', 'arm64'], "deps": ['forky-gcc']},
    'forky-gcc-rig-rdev': {"path": 'forky/gcc/rig/rdev', "archs": ['amd64', 'arm64'], "deps": ['forky-gcc-rig']},
    'forky-gcc-rig-rdev-duckdb': {"path": 'forky/gcc/rig/rdev/duckdb', "archs": ['amd64', 'arm64'], "deps": ['forky-gcc-rig-rdev']},
    'p3m-bookworm': {"path": 'p3m-bookworm', "archs": ['amd64'], "deps": ['p3m-bookworm-rbuild']},
    'p3m-bookworm-rbuild': {"path": 'p3m-bookworm-rbuild', "archs": ['amd64'], "deps": []},
    'p3m-centos7': {"path": 'p3m-centos7', "archs": ['amd64'], "deps": []},
    'p3m-jammy': {"path": 'p3m-jammy', "archs": ['amd64'], "deps": []},
    'p3m-manylinux': {"path": 'p3m-manylinux', "archs": ['amd64', 'arm64'], "deps": []},
    'p3m-noble': {"path": 'p3m-noble', "archs": ['amd64', 'arm64'], "deps": []},
    'p3m-opensuse': {"path": 'p3m-opensuse', "archs": ['amd64'], "deps": []},
    'p3m-resolute': {"path": 'p3m-resolute', "archs": ['amd64', 'arm64'], "deps": []},
    'p3m-rhel10': {"path": 'p3m-rhel10', "archs": ['amd64', 'arm64'], "deps": ['p3m-rhel10-rbuild']},
    'p3m-rhel10-rbuild': {"path": 'p3m-rhel10-rbuild', "archs": ['amd64', 'arm64'], "deps": []},
    'p3m-rhel8': {"path": 'p3m-rhel8', "archs": ['amd64'], "deps": []},
    'p3m-rhel9': {"path": 'p3m-rhel9', "archs": ['amd64', 'arm64'], "deps": []},
    'p3m-trixie': {"path": 'p3m-trixie', "archs": ['amd64'], "deps": []},
    'r-minimal': {"path": 'r-minimal', "archs": ['amd64', 'arm64'], "deps": []},
    'rchk-igraph': {"path": 'rchk-igraph', "archs": ['amd64'], "deps": []},
    'rig-debian': {"path": 'rig-debian', "archs": ['amd64'], "deps": []},
    'rig-rocky8': {"path": 'rig-rocky8', "archs": ['amd64'], "deps": []},
    'rig-ubuntu': {"path": 'rig-ubuntu', "archs": ['amd64'], "deps": []},
    'rig-ubuntu-dbi': {"path": 'rig-ubuntu/dbi', "archs": ['amd64'], "deps": ['rig-ubuntu']},
    'rig-ubuntu-dm': {"path": 'rig-ubuntu/dm', "archs": ['amd64'], "deps": ['rig-ubuntu']},
    'rig-ubuntu-duckdb': {"path": 'rig-ubuntu/duckdb', "archs": ['amd64'], "deps": ['rig-ubuntu']},
    'rig-ubuntu-duckdb-dev': {"path": 'rig-ubuntu/duckdb/dev', "archs": ['amd64'], "deps": ['rig-ubuntu-duckdb']},
    'rig-ubuntu-duckdb4': {"path": 'rig-ubuntu/duckdb4', "archs": ['amd64'], "deps": ['rig-ubuntu']},
    'rig-ubuntu-igraph': {"path": 'rig-ubuntu/igraph', "archs": ['amd64'], "deps": ['rig-ubuntu']},
    'rig-ubuntu-r-postgres': {"path": 'rig-ubuntu/r-postgres', "archs": ['amd64'], "deps": ['rig-ubuntu']},
    'rig-ubuntu-revdepcheck': {"path": 'rig-ubuntu/revdepcheck', "archs": ['amd64'], "deps": ['rig-ubuntu']},
    'ubuntu24': {"path": 'ubuntu24', "archs": ['amd64', 'arm64'], "deps": []},
    'ubuntu24-msfonts': {"path": 'ubuntu24/msfonts', "archs": ['amd64'], "deps": ['ubuntu24']},
    'ubuntu24-pak': {"path": 'ubuntu24/pak', "archs": ['amd64', 'arm64'], "deps": ['ubuntu24']},
    'ubuntu24-pak-rlang': {"path": 'ubuntu24/pak/rlang', "archs": ['amd64', 'arm64'], "deps": ['ubuntu24-pak']},
    'ubuntu24-pak-rlang2': {"path": 'ubuntu24/pak/rlang2', "archs": ['amd64', 'arm64'], "deps": ['ubuntu24-pak']},
    'ubuntu24-rig': {"path": 'ubuntu24/rig', "archs": ['amd64', 'arm64'], "deps": ['ubuntu24']},
    'ubuntu24-rig-rdev': {"path": 'ubuntu24/rig/rdev', "archs": ['amd64', 'arm64'], "deps": ['ubuntu24-rig']},
    'ubuntu24-rig-rdev-dc': {"path": 'ubuntu24/rig/rdev/dc', "archs": ['amd64', 'arm64'], "deps": ['ubuntu24-rig-rdev']},
    'ubuntu24-rig-rdev-dc-dt': {"path": 'ubuntu24/rig/rdev/dc/dt', "archs": ['amd64', 'arm64'], "deps": ['ubuntu24-rig-rdev-dc']},
    'ubuntu24-rig-rdev-gcc14': {"path": 'ubuntu24/rig/rdev/gcc14', "archs": ['amd64', 'arm64'], "deps": ['ubuntu24-rig-rdev']},
    'ubuntu24-rig-rdev-gcc14-duckdb': {"path": 'ubuntu24/rig/rdev/gcc14/duckdb', "archs": ['amd64', 'arm64'], "deps": ['ubuntu24-rig-rdev-gcc14']},
    'ubuntu24-rig-rrel': {"path": 'ubuntu24/rig/rrel', "archs": ['amd64', 'arm64'], "deps": ['ubuntu24-rig']},
    'ubuntu24-rig-rrel-dc': {"path": 'ubuntu24/rig/rrel/dc', "archs": ['amd64', 'arm64'], "deps": ['ubuntu24-rig-rrel']},
    'ubuntu24-rig-rrel-dc-dt': {"path": 'ubuntu24/rig/rrel/dc/dt', "archs": ['amd64', 'arm64'], "deps": ['ubuntu24-rig-rrel-dc']},
    'ubuntu24-rig-rrel-dc-dt-dm': {"path": 'ubuntu24/rig/rrel/dc/dt/dm', "archs": ['amd64', 'arm64'], "deps": ['ubuntu24-rig-rrel-dc-dt']},
    'ubuntu24-rig-rrel-dc-dt-pkgcache': {"path": 'ubuntu24/rig/rrel/dc/dt/pkgcache', "archs": ['amd64', 'arm64'], "deps": ['ubuntu24-rig-rrel-dc-dt']},
}

# Topological build order: dependencies before dependents.  (generated)
TOPO = [
    'alma9',
    'clang18-duckdb',
    'forky',
    'p3m-bookworm-rbuild',
    'p3m-centos7',
    'p3m-jammy',
    'p3m-manylinux',
    'p3m-noble',
    'p3m-opensuse',
    'p3m-resolute',
    'p3m-rhel10-rbuild',
    'p3m-rhel8',
    'p3m-rhel9',
    'p3m-trixie',
    'r-minimal',
    'rchk-igraph',
    'rig-debian',
    'rig-rocky8',
    'rig-ubuntu',
    'ubuntu24',
    'alma9-rig',
    'forky-gcc',
    'p3m-bookworm',
    'p3m-rhel10',
    'rig-ubuntu-dbi',
    'rig-ubuntu-dm',
    'rig-ubuntu-duckdb',
    'rig-ubuntu-duckdb4',
    'rig-ubuntu-igraph',
    'rig-ubuntu-r-postgres',
    'rig-ubuntu-revdepcheck',
    'ubuntu24-msfonts',
    'ubuntu24-pak',
    'ubuntu24-rig',
    'alma9-rig-rrel',
    'forky-gcc-rig',
    'rig-ubuntu-duckdb-dev',
    'ubuntu24-pak-rlang',
    'ubuntu24-pak-rlang2',
    'ubuntu24-rig-rdev',
    'ubuntu24-rig-rrel',
    'alma9-rig-rrel-coinor',
    'forky-gcc-rig-rdev',
    'ubuntu24-rig-rdev-dc',
    'ubuntu24-rig-rdev-gcc14',
    'ubuntu24-rig-rrel-dc',
    'forky-gcc-rig-rdev-duckdb',
    'ubuntu24-rig-rdev-dc-dt',
    'ubuntu24-rig-rdev-gcc14-duckdb',
    'ubuntu24-rig-rrel-dc-dt',
    'ubuntu24-rig-rrel-dc-dt-dm',
    'ubuntu24-rig-rrel-dc-dt-pkgcache',
]


def changed_paths():
    base = os.environ.get("BASE_SHA")
    head = os.environ.get("HEAD_SHA") or "HEAD"
    rng = base + "..." + head if base else head
    out = subprocess.run(
        ["git", "diff", "--name-only", rng],
        capture_output=True, text=True, check=True,
    ).stdout
    return [p.strip() for p in out.splitlines() if p.strip()]


def image_for_path(path):
    # The image whose directory is the longest matching prefix of the path.
    best = None
    for img, meta in IMAGES.items():
        d = meta["path"]
        if path == d or path.startswith(d + "/"):
            if best is None or len(meta["path"]) > len(IMAGES[best]["path"]):
                best = img
    return best


def downstream_closure(seed):
    reverse = {img: [] for img in IMAGES}
    for img, meta in IMAGES.items():
        for dep in meta["deps"]:
            if dep in reverse:
                reverse[dep].append(img)
    result = set(seed)
    stack = list(seed)
    while stack:
        cur = stack.pop()
        for dependent in reverse.get(cur, []):
            if dependent not in result:
                result.add(dependent)
                stack.append(dependent)
    return result


def build(img):
    meta = IMAGES[img]
    path = meta["path"]
    if "amd64" not in meta["archs"]:
        print("::notice::Skipping " + img + " on PR (no amd64 build; archs="
              + repr(meta["archs"]) + ")")
        return
    arch = "amd64"
    # date.txt drives cache invalidation and is COPYed by many Dockerfiles.
    with open(os.path.join(path, "date.txt"), "w") as fh:
        fh.write(datetime.date.today().isoformat() + "\n")
    full = REGISTRY + "/" + REPO_NAME + "/" + img
    # Plain `docker build` (default driver) loads into the local image store, so
    # later dependents resolve FROM / COPY --from locally. No --pull (use local
    # upstreams when present), no --push.
    cmd = [
        "docker", "build",
        "--build-arg", "TARGETARCH=" + arch,
        "-t", full + ":latest-" + arch,
        "-t", full + ":latest",
        path,
    ]
    print("::group::docker build " + img + " (" + arch + ")", flush=True)
    print(" ".join(cmd), flush=True)
    subprocess.run(cmd, check=True)
    print("::endgroup::", flush=True)


def main():
    seed = set()
    for path in changed_paths():
        img = image_for_path(path)
        if img:
            seed.add(img)
    if not seed:
        print("No changed images detected; nothing to build.")
        return
    to_build = downstream_closure(seed)
    ordered = [img for img in TOPO if img in to_build]
    print("Changed images:  " + ", ".join(sorted(seed)))
    print("Build order (changed + downstream):  " + ", ".join(ordered))
    for img in ordered:
        build(img)
    print("Successfully built " + str(len(ordered)) + " image(s) with no push.")


if __name__ == "__main__":
    main()
