#!/usr/bin/env bash
# Generated by generate_stages.py, do not edit by hand
# Run 'make pr-build-script' to regenerate this file
#
# Pull-request build check (no push).
#
# Build every CHANGED image and all its DOWNSTREAM dependents, in dependency
# order, in a single job. Each image is built into the local docker image store
# and tagged with its registry references, so a dependent's FROM / COPY --from
# resolves against the just-built local image. Unchanged upstream dependencies
# are pulled from the registry (published on main). Nothing is pushed.
set -euo pipefail

REGISTRY="ghcr.io"
REPO_NAME="${REPO_NAME:-cynkra/docker-images}"

# Topological build order: dependencies before dependents.  (generated)
TOPO=(
    "alma9"
    "clang18-duckdb"
    "forky"
    "p3m-bookworm-rbuild"
    "p3m-centos7"
    "p3m-jammy"
    "p3m-manylinux"
    "p3m-noble"
    "p3m-opensuse"
    "p3m-resolute"
    "p3m-rhel10-rbuild"
    "p3m-rhel8"
    "p3m-rhel9"
    "p3m-trixie"
    "r-minimal"
    "rchk-igraph"
    "rig-debian"
    "rig-rocky8"
    "rig-ubuntu"
    "ubuntu24"
    "alma9-rig"
    "forky-gcc"
    "p3m-bookworm"
    "p3m-rhel10"
    "rig-ubuntu-dbi"
    "rig-ubuntu-dm"
    "rig-ubuntu-duckdb"
    "rig-ubuntu-duckdb4"
    "rig-ubuntu-igraph"
    "rig-ubuntu-r-postgres"
    "rig-ubuntu-revdepcheck"
    "ubuntu24-msfonts"
    "ubuntu24-pak"
    "ubuntu24-rig"
    "alma9-rig-rrel"
    "forky-gcc-rig"
    "rig-ubuntu-duckdb-dev"
    "ubuntu24-pak-rlang"
    "ubuntu24-pak-rlang2"
    "ubuntu24-rig-rdev"
    "ubuntu24-rig-rrel"
    "alma9-rig-rrel-coinor"
    "forky-gcc-rig-rdev"
    "ubuntu24-rig-rdev-dc"
    "ubuntu24-rig-rdev-gcc14"
    "ubuntu24-rig-rrel-dc"
    "forky-gcc-rig-rdev-duckdb"
    "ubuntu24-rig-rdev-dc-dt"
    "ubuntu24-rig-rdev-gcc14-duckdb"
    "ubuntu24-rig-rrel-dc-dt"
    "ubuntu24-rig-rrel-dc-dt-dm"
    "ubuntu24-rig-rrel-dc-dt-pkgcache"
)
# image -> directory.  (generated)
declare -A PATHS=(
    ["alma9"]="alma9"
    ["alma9-rig"]="alma9/rig"
    ["alma9-rig-rrel"]="alma9/rig/rrel"
    ["alma9-rig-rrel-coinor"]="alma9/rig/rrel/coinor"
    ["clang18-duckdb"]="clang18-duckdb"
    ["forky"]="forky"
    ["forky-gcc"]="forky/gcc"
    ["forky-gcc-rig"]="forky/gcc/rig"
    ["forky-gcc-rig-rdev"]="forky/gcc/rig/rdev"
    ["forky-gcc-rig-rdev-duckdb"]="forky/gcc/rig/rdev/duckdb"
    ["p3m-bookworm"]="p3m-bookworm"
    ["p3m-bookworm-rbuild"]="p3m-bookworm-rbuild"
    ["p3m-centos7"]="p3m-centos7"
    ["p3m-jammy"]="p3m-jammy"
    ["p3m-manylinux"]="p3m-manylinux"
    ["p3m-noble"]="p3m-noble"
    ["p3m-opensuse"]="p3m-opensuse"
    ["p3m-resolute"]="p3m-resolute"
    ["p3m-rhel10"]="p3m-rhel10"
    ["p3m-rhel10-rbuild"]="p3m-rhel10-rbuild"
    ["p3m-rhel8"]="p3m-rhel8"
    ["p3m-rhel9"]="p3m-rhel9"
    ["p3m-trixie"]="p3m-trixie"
    ["r-minimal"]="r-minimal"
    ["rchk-igraph"]="rchk-igraph"
    ["rig-debian"]="rig-debian"
    ["rig-rocky8"]="rig-rocky8"
    ["rig-ubuntu"]="rig-ubuntu"
    ["rig-ubuntu-dbi"]="rig-ubuntu/dbi"
    ["rig-ubuntu-dm"]="rig-ubuntu/dm"
    ["rig-ubuntu-duckdb"]="rig-ubuntu/duckdb"
    ["rig-ubuntu-duckdb-dev"]="rig-ubuntu/duckdb/dev"
    ["rig-ubuntu-duckdb4"]="rig-ubuntu/duckdb4"
    ["rig-ubuntu-igraph"]="rig-ubuntu/igraph"
    ["rig-ubuntu-r-postgres"]="rig-ubuntu/r-postgres"
    ["rig-ubuntu-revdepcheck"]="rig-ubuntu/revdepcheck"
    ["ubuntu24"]="ubuntu24"
    ["ubuntu24-msfonts"]="ubuntu24/msfonts"
    ["ubuntu24-pak"]="ubuntu24/pak"
    ["ubuntu24-pak-rlang"]="ubuntu24/pak/rlang"
    ["ubuntu24-pak-rlang2"]="ubuntu24/pak/rlang2"
    ["ubuntu24-rig"]="ubuntu24/rig"
    ["ubuntu24-rig-rdev"]="ubuntu24/rig/rdev"
    ["ubuntu24-rig-rdev-dc"]="ubuntu24/rig/rdev/dc"
    ["ubuntu24-rig-rdev-dc-dt"]="ubuntu24/rig/rdev/dc/dt"
    ["ubuntu24-rig-rdev-gcc14"]="ubuntu24/rig/rdev/gcc14"
    ["ubuntu24-rig-rdev-gcc14-duckdb"]="ubuntu24/rig/rdev/gcc14/duckdb"
    ["ubuntu24-rig-rrel"]="ubuntu24/rig/rrel"
    ["ubuntu24-rig-rrel-dc"]="ubuntu24/rig/rrel/dc"
    ["ubuntu24-rig-rrel-dc-dt"]="ubuntu24/rig/rrel/dc/dt"
    ["ubuntu24-rig-rrel-dc-dt-dm"]="ubuntu24/rig/rrel/dc/dt/dm"
    ["ubuntu24-rig-rrel-dc-dt-pkgcache"]="ubuntu24/rig/rrel/dc/dt/pkgcache"
)
# image -> space-separated local dependencies.  (generated)
declare -A DEPS=(
    ["alma9"]=""
    ["alma9-rig"]="alma9"
    ["alma9-rig-rrel"]="alma9-rig"
    ["alma9-rig-rrel-coinor"]="alma9-rig-rrel"
    ["clang18-duckdb"]=""
    ["forky"]=""
    ["forky-gcc"]="forky"
    ["forky-gcc-rig"]="forky-gcc"
    ["forky-gcc-rig-rdev"]="forky-gcc-rig"
    ["forky-gcc-rig-rdev-duckdb"]="forky-gcc-rig-rdev"
    ["p3m-bookworm"]="p3m-bookworm-rbuild"
    ["p3m-bookworm-rbuild"]=""
    ["p3m-centos7"]=""
    ["p3m-jammy"]=""
    ["p3m-manylinux"]=""
    ["p3m-noble"]=""
    ["p3m-opensuse"]=""
    ["p3m-resolute"]=""
    ["p3m-rhel10"]="p3m-rhel10-rbuild"
    ["p3m-rhel10-rbuild"]=""
    ["p3m-rhel8"]=""
    ["p3m-rhel9"]=""
    ["p3m-trixie"]=""
    ["r-minimal"]=""
    ["rchk-igraph"]=""
    ["rig-debian"]=""
    ["rig-rocky8"]=""
    ["rig-ubuntu"]=""
    ["rig-ubuntu-dbi"]="rig-ubuntu"
    ["rig-ubuntu-dm"]="rig-ubuntu"
    ["rig-ubuntu-duckdb"]="rig-ubuntu"
    ["rig-ubuntu-duckdb-dev"]="rig-ubuntu-duckdb"
    ["rig-ubuntu-duckdb4"]="rig-ubuntu"
    ["rig-ubuntu-igraph"]="rig-ubuntu"
    ["rig-ubuntu-r-postgres"]="rig-ubuntu"
    ["rig-ubuntu-revdepcheck"]="rig-ubuntu"
    ["ubuntu24"]=""
    ["ubuntu24-msfonts"]="ubuntu24"
    ["ubuntu24-pak"]="ubuntu24"
    ["ubuntu24-pak-rlang"]="ubuntu24-pak"
    ["ubuntu24-pak-rlang2"]="ubuntu24-pak"
    ["ubuntu24-rig"]="ubuntu24"
    ["ubuntu24-rig-rdev"]="ubuntu24-rig"
    ["ubuntu24-rig-rdev-dc"]="ubuntu24-rig-rdev"
    ["ubuntu24-rig-rdev-dc-dt"]="ubuntu24-rig-rdev-dc"
    ["ubuntu24-rig-rdev-gcc14"]="ubuntu24-rig-rdev"
    ["ubuntu24-rig-rdev-gcc14-duckdb"]="ubuntu24-rig-rdev-gcc14"
    ["ubuntu24-rig-rrel"]="ubuntu24-rig"
    ["ubuntu24-rig-rrel-dc"]="ubuntu24-rig-rrel"
    ["ubuntu24-rig-rrel-dc-dt"]="ubuntu24-rig-rrel-dc"
    ["ubuntu24-rig-rrel-dc-dt-dm"]="ubuntu24-rig-rrel-dc-dt"
    ["ubuntu24-rig-rrel-dc-dt-pkgcache"]="ubuntu24-rig-rrel-dc-dt"
)
# image -> space-separated architectures.  (generated)
declare -A ARCHS=(
    ["alma9"]="amd64 arm64"
    ["alma9-rig"]="amd64 arm64"
    ["alma9-rig-rrel"]="amd64 arm64"
    ["alma9-rig-rrel-coinor"]="amd64 arm64"
    ["clang18-duckdb"]="amd64"
    ["forky"]="amd64 arm64"
    ["forky-gcc"]="amd64 arm64"
    ["forky-gcc-rig"]="amd64 arm64"
    ["forky-gcc-rig-rdev"]="amd64 arm64"
    ["forky-gcc-rig-rdev-duckdb"]="amd64 arm64"
    ["p3m-bookworm"]="amd64"
    ["p3m-bookworm-rbuild"]="amd64"
    ["p3m-centos7"]="amd64"
    ["p3m-jammy"]="amd64"
    ["p3m-manylinux"]="amd64 arm64"
    ["p3m-noble"]="amd64 arm64"
    ["p3m-opensuse"]="amd64"
    ["p3m-resolute"]="amd64 arm64"
    ["p3m-rhel10"]="amd64 arm64"
    ["p3m-rhel10-rbuild"]="amd64 arm64"
    ["p3m-rhel8"]="amd64"
    ["p3m-rhel9"]="amd64 arm64"
    ["p3m-trixie"]="amd64"
    ["r-minimal"]="amd64 arm64"
    ["rchk-igraph"]="amd64"
    ["rig-debian"]="amd64"
    ["rig-rocky8"]="amd64"
    ["rig-ubuntu"]="amd64"
    ["rig-ubuntu-dbi"]="amd64"
    ["rig-ubuntu-dm"]="amd64"
    ["rig-ubuntu-duckdb"]="amd64"
    ["rig-ubuntu-duckdb-dev"]="amd64"
    ["rig-ubuntu-duckdb4"]="amd64"
    ["rig-ubuntu-igraph"]="amd64"
    ["rig-ubuntu-r-postgres"]="amd64"
    ["rig-ubuntu-revdepcheck"]="amd64"
    ["ubuntu24"]="amd64 arm64"
    ["ubuntu24-msfonts"]="amd64"
    ["ubuntu24-pak"]="amd64 arm64"
    ["ubuntu24-pak-rlang"]="amd64 arm64"
    ["ubuntu24-pak-rlang2"]="amd64 arm64"
    ["ubuntu24-rig"]="amd64 arm64"
    ["ubuntu24-rig-rdev"]="amd64 arm64"
    ["ubuntu24-rig-rdev-dc"]="amd64 arm64"
    ["ubuntu24-rig-rdev-dc-dt"]="amd64 arm64"
    ["ubuntu24-rig-rdev-gcc14"]="amd64 arm64"
    ["ubuntu24-rig-rdev-gcc14-duckdb"]="amd64 arm64"
    ["ubuntu24-rig-rrel"]="amd64 arm64"
    ["ubuntu24-rig-rrel-dc"]="amd64 arm64"
    ["ubuntu24-rig-rrel-dc-dt"]="amd64 arm64"
    ["ubuntu24-rig-rrel-dc-dt-dm"]="amd64 arm64"
    ["ubuntu24-rig-rrel-dc-dt-pkgcache"]="amd64 arm64"
)

# Echo the image whose directory is the longest matching prefix of $1.
image_for_path() {
  local path="$1" best="" bestlen=0 img d
  for img in "${TOPO[@]}"; do
    d="${PATHS[$img]}"
    if [ "$path" = "$d" ] || [ "${path#"$d"/}" != "$path" ]; then
      if [ "${#d}" -gt "$bestlen" ]; then best="$img"; bestlen="${#d}"; fi
    fi
  done
  printf '%s' "$best"
}

# Build one image locally (no push), tagging it with its registry references so
# later dependents resolve FROM / COPY --from against this local image.
build_image() {
  local img="$1" path="${PATHS[$img]}" full
  case " ${ARCHS[$img]} " in
    *" amd64 "*) ;;
    *) echo "::notice::Skipping ${img} on PR (no amd64 build; archs=${ARCHS[$img]})"; return 0 ;;
  esac
  date -Idate > "${path}/date.txt"
  full="${REGISTRY}/${REPO_NAME}/${img}"
  echo "::group::docker build ${img} (amd64)"
  docker build --build-arg TARGETARCH=amd64 \
    -t "${full}:latest-amd64" -t "${full}:latest" "${path}"
  echo "::endgroup::"
}

main() {
  local base="${BASE_SHA:-}" head="${HEAD_SHA:-HEAD}" rng
  if [ -n "$base" ]; then rng="${base}...${head}"; else rng="$head"; fi

  # Seed = changed images.
  declare -A seed=()
  local f img
  while IFS= read -r f; do
    [ -n "$f" ] || continue
    img="$(image_for_path "$f")"
    [ -n "$img" ] && seed["$img"]=1
  done < <(git diff --name-only "$rng")

  if [ "${#seed[@]}" -eq 0 ]; then
    echo "No changed images detected; nothing to build."
    return 0
  fi

  # Reverse adjacency (dependency -> dependents) for the downstream closure.
  declare -A rdeps=()
  local dep
  for img in "${TOPO[@]}"; do
    for dep in ${DEPS[$img]:-}; do
      rdeps["$dep"]="${rdeps[$dep]:-} ${img}"
    done
  done

  # Transitive downstream closure of the seed.
  declare -A inset=()
  local worklist=() cur d
  for img in "${!seed[@]}"; do inset["$img"]=1; worklist+=("$img"); done
  while [ "${#worklist[@]}" -gt 0 ]; do
    cur="${worklist[0]}"; worklist=("${worklist[@]:1}")
    for d in ${rdeps["$cur"]:-}; do
      if [ -z "${inset[$d]:-}" ]; then inset["$d"]=1; worklist+=("$d"); fi
    done
  done

  # Build in topological order.
  local ordered=()
  for img in "${TOPO[@]}"; do
    [ -n "${inset[$img]:-}" ] && ordered+=("$img")
  done
  echo "Changed images:  ${!seed[*]}"
  echo "Build order (changed + downstream):  ${ordered[*]}"
  for img in "${ordered[@]}"; do build_image "$img"; done
  echo "Successfully built ${#ordered[@]} image(s) with no push."
}

main "$@"
