on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        run: |
          echo "tag=$((grep ARG ${{ inputs.image }}/Dockerfile || grep FROM ${{ inputs.image }}/Dockerfile) | sed 's/.*[:=]\(.*\)/\1/')" >> "$GITHUB_OUTPUT"
      # setup buildx is needed to use cache
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ inputs.image }}/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPO_NAME }}/${{ inputs.image }}:${{ steps.meta.outputs.tag }}
            ${{ env.REGISTRY }}/${{ env.REPO_NAME }}/${{ inputs.image }}:latest
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.REPO_NAME }}/${{ inputs.image }}:latest
          cache-to: type=inline
