name: Create and publish a Docker image

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.repository }}

jobs:
  stage-1:
    strategy:
      matrix:
        image:
          - tofutf
          - rig-ubuntu
    uses: cynkra/docker-images/.github/workflows/publish.yml@main
    with:
      image: ${{ matrix.image }}

  stage-2:
    needs: stage-1
    strategy:
      matrix:
        image:
          - rig-rocky8
    uses: cynkra/docker-images/.github/workflows/publish.yml@main
    with:
      image: ${{ matrix.image }}
