name: Create and publish a Docker image

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch: null
  schedule:
    - cron: 0 0 * * *

env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.repository }}

jobs:
  alma9:
    uses: cynkra/docker-images/.github/workflows/publish.yml@main
    with:
      path: alma9
      image_name: alma9
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  rig-alma9:
    needs:
      - alma9
    uses: cynkra/docker-images/.github/workflows/publish.yml@main
    with:
      path: alma9/rig
      image_name: alma9-rig
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  rrel-rig-alma9:
    needs:
      - rig-alma9
    uses: cynkra/docker-images/.github/workflows/publish.yml@main
    with:
      path: alma9/rig/rrel
      image_name: alma9-rig-rrel
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  coinor-rrel-rig-alma9:
    needs:
      - rrel-rig-alma9
    uses: cynkra/docker-images/.github/workflows/publish.yml@main
    with:
      path: alma9/rig/rrel/coinor
      image_name: alma9-rig-rrel-coinor
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build-dust:
    uses: cynkra/docker-images/.github/workflows/publish.yml@main
    with:
      path: build-dust
      image_name: build-dust
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  clang18-duckdb:
    uses: cynkra/docker-images/.github/workflows/publish.yml@main
    with:
      path: clang18-duckdb
      image_name: clang18-duckdb
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  dust:
    needs:
      - build-dust
    uses: cynkra/docker-images/.github/workflows/publish.yml@main
    with:
      path: dust
      image_name: dust
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  r-minimal:
    uses: cynkra/docker-images/.github/workflows/publish.yml@main
    with:
      path: r-minimal
      image_name: r-minimal
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  rchk-igraph:
    uses: cynkra/docker-images/.github/workflows/publish.yml@main
    with:
      path: rchk-igraph
      image_name: rchk-igraph
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  rig-debian:
    uses: cynkra/docker-images/.github/workflows/publish.yml@main
    with:
      path: rig-debian
      image_name: rig-debian
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  rig-rocky8:
    uses: cynkra/docker-images/.github/workflows/publish.yml@main
    with:
      path: rig-rocky8
      image_name: rig-rocky8
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  rig-ubuntu:
    uses: cynkra/docker-images/.github/workflows/publish.yml@main
    with:
      path: rig-ubuntu
      image_name: rig-ubuntu
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  dbi-rig-ubuntu:
    needs:
      - rig-ubuntu
    uses: cynkra/docker-images/.github/workflows/publish.yml@main
    with:
      path: rig-ubuntu/dbi
      image_name: rig-ubuntu-dbi
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  dm-rig-ubuntu:
    needs:
      - rig-ubuntu
    uses: cynkra/docker-images/.github/workflows/publish.yml@main
    with:
      path: rig-ubuntu/dm
      image_name: rig-ubuntu-dm
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  duckdb-rig-ubuntu:
    needs:
      - rig-ubuntu
    uses: cynkra/docker-images/.github/workflows/publish.yml@main
    with:
      path: rig-ubuntu/duckdb
      image_name: rig-ubuntu-duckdb
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  dev-duckdb-rig-ubuntu:
    needs:
      - duckdb-rig-ubuntu
    uses: cynkra/docker-images/.github/workflows/publish.yml@main
    with:
      path: rig-ubuntu/duckdb/dev
      image_name: rig-ubuntu-duckdb-dev
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  duckdb4-rig-ubuntu:
    needs:
      - rig-ubuntu
    uses: cynkra/docker-images/.github/workflows/publish.yml@main
    with:
      path: rig-ubuntu/duckdb4
      image_name: rig-ubuntu-duckdb4
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  igraph-rig-ubuntu:
    needs:
      - rig-ubuntu
    uses: cynkra/docker-images/.github/workflows/publish.yml@main
    with:
      path: rig-ubuntu/igraph
      image_name: rig-ubuntu-igraph
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  r-postgres-rig-ubuntu:
    needs:
      - rig-ubuntu
    uses: cynkra/docker-images/.github/workflows/publish.yml@main
    with:
      path: rig-ubuntu/r-postgres
      image_name: rig-ubuntu-r-postgres
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  revdepcheck-rig-ubuntu:
    needs:
      - rig-ubuntu
    uses: cynkra/docker-images/.github/workflows/publish.yml@main
    with:
      path: rig-ubuntu/revdepcheck
      image_name: rig-ubuntu-revdepcheck
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  rigraph-san:
    uses: cynkra/docker-images/.github/workflows/publish.yml@main
    with:
      path: rigraph-san
      image_name: rigraph-san
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  sops-age:
    uses: cynkra/docker-images/.github/workflows/publish.yml@main
    with:
      path: sops-age
      image_name: sops-age
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  sssd-almalinux:
    uses: cynkra/docker-images/.github/workflows/publish.yml@main
    with:
      path: sssd-almalinux
      image_name: sssd-almalinux
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  tofutf:
    uses: cynkra/docker-images/.github/workflows/publish.yml@main
    with:
      path: tofutf
      image_name: tofutf
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  ubuntu24:
    uses: cynkra/docker-images/.github/workflows/publish.yml@main
    with:
      path: ubuntu24
      image_name: ubuntu24
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  msfonts-ubuntu24:
    needs:
      - ubuntu24
    uses: cynkra/docker-images/.github/workflows/publish.yml@main
    with:
      path: ubuntu24/msfonts
      image_name: ubuntu24-msfonts
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  rig-ubuntu24:
    needs:
      - ubuntu24
    uses: cynkra/docker-images/.github/workflows/publish.yml@main
    with:
      path: ubuntu24/rig
      image_name: ubuntu24-rig
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  rdev-rig-ubuntu24:
    needs:
      - rig-ubuntu24
    uses: cynkra/docker-images/.github/workflows/publish.yml@main
    with:
      path: ubuntu24/rig/rdev
      image_name: ubuntu24-rig-rdev
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  dc-rdev-rig-ubuntu24:
    needs:
      - dust
      - rdev-rig-ubuntu24
    uses: cynkra/docker-images/.github/workflows/publish.yml@main
    with:
      path: ubuntu24/rig/rdev/dc
      image_name: ubuntu24-rig-rdev-dc
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  dt-dc-rdev-rig-ubuntu24:
    needs:
      - dc-rdev-rig-ubuntu24
    uses: cynkra/docker-images/.github/workflows/publish.yml@main
    with:
      path: ubuntu24/rig/rdev/dc/dt
      image_name: ubuntu24-rig-rdev-dc-dt
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  gcc14-rdev-rig-ubuntu24:
    needs:
      - rdev-rig-ubuntu24
    uses: cynkra/docker-images/.github/workflows/publish.yml@main
    with:
      path: ubuntu24/rig/rdev/gcc14
      image_name: ubuntu24-rig-rdev-gcc14
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  duckdb-gcc14-rdev-rig-ubuntu24:
    needs:
      - gcc14-rdev-rig-ubuntu24
    uses: cynkra/docker-images/.github/workflows/publish.yml@main
    with:
      path: ubuntu24/rig/rdev/gcc14/duckdb
      image_name: ubuntu24-rig-rdev-gcc14-duckdb
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  rrel-rig-ubuntu24:
    needs:
      - rig-ubuntu24
    uses: cynkra/docker-images/.github/workflows/publish.yml@main
    with:
      path: ubuntu24/rig/rrel
      image_name: ubuntu24-rig-rrel
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  dc-rrel-rig-ubuntu24:
    needs:
      - dust
      - rrel-rig-ubuntu24
    uses: cynkra/docker-images/.github/workflows/publish.yml@main
    with:
      path: ubuntu24/rig/rrel/dc
      image_name: ubuntu24-rig-rrel-dc
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  dt-dc-rrel-rig-ubuntu24:
    needs:
      - dc-rrel-rig-ubuntu24
    uses: cynkra/docker-images/.github/workflows/publish.yml@main
    with:
      path: ubuntu24/rig/rrel/dc/dt
      image_name: ubuntu24-rig-rrel-dc-dt
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  dm-dt-dc-rrel-rig-ubuntu24:
    needs:
      - dt-dc-rrel-rig-ubuntu24
    uses: cynkra/docker-images/.github/workflows/publish.yml@main
    with:
      path: ubuntu24/rig/rrel/dc/dt/dm
      image_name: ubuntu24-rig-rrel-dc-dt-dm
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
